import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Layout } from '@/screens/layout'

import MainProvider from '../providers/MainProvider'
import '../styles/global.scss'

const inter = Inter({
	weight: ['300', '400', '500', '600', '700'],
	style: 'normal',
	variable: '--font-inter',
	subsets: ['cyrillic'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Строй Дом Стиль',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='ru'
			style={{
				fontFamily: inter.style.fontFamily,
			}}
		>
			<body>
				<MainProvider>
					<Layout>{children}</Layout>
				</MainProvider>
			</body>
		</html>
	)
}
